import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
assert.equal(fs.existsSync(path.join(root,'src/shared/audio-devices.js')),false);
const files=['popup.html','studio.html','offscreen.html','src/popup/popup.js','src/studio/studio.js','src/background/service-worker.js','src/offscreen/offscreen.js','src/shared/presets.js'];
const runtime=files.map(read).join('\n');
for (const token of ['outputDeviceId','outputRouteStatus','setSinkId','createMediaStreamDestination','processedOutput','audioOutputSelect','topbarOutputDevice','domainOutputRoutes']) assert.equal(runtime.includes(token),false,`removed output-routing token remains: ${token}`);
const offscreen=read('src/offscreen/offscreen.js');
assert.match(offscreen,/SET_MONITORING_ACTIVE/);
assert.match(offscreen,/monitoringActive = false/);
assert.match(offscreen,/createMonitoringNodes\(\)/);
const startup=offscreen.slice(offscreen.indexOf('async start('),offscreen.indexOf('async stop('));
assert.doesNotMatch(startup,/this\.inputAnalyser = this\.createRtaAnalyser/);
assert.doesNotMatch(startup,/this\.createStereoBandMeters\(\)/);
assert.match(startup,/if \(this\.monitoringActive\) this\.createMonitoringNodes\(\)/);
assert.match(offscreen,/destroyMonitoringNodes\(\)/);
assert.match(offscreen,/this\.source\.connect\(this\.inputGain\)/);
assert.match(offscreen,/rebuildGraphSafely/);
assert.match(offscreen,/ensureOutputShell/);
assert.equal((offscreen.match(/this\.outputShellConnected = false;/g) || []).length,2);
assert.match(offscreen,/disconnectProcessingGraph/);
assert.match(offscreen,/this\.source\.connect\(this\.bypassGain\)\.connect\(this\.outputMixGain\)\.connect\(this\.context\.destination\)/);
assert.match(offscreen,/this\.source\?\.disconnect\(this\.inputAnalyser\)/);
assert.match(offscreen,/this\.monitoringOutputTap\?\.disconnect\(this\.outputAnalyser\)/);
assert.match(offscreen,/!this\.monitoringActive/);
assert.match(offscreen,/const meters = metersOverride \|\| this\.state\.meters \|\| createSilentMeters\(\)/);
assert.doesNotMatch(offscreen,/getPublicState\([^)]*\)\s*\{[^}]*computeMeters/s);
const graphStart=offscreen.indexOf('connectGraph({');
const graphEnd=offscreen.indexOf('\n  createMonitoringNodes()',graphStart);
const graphSection=offscreen.slice(graphStart,graphEnd);
assert.doesNotMatch(graphSection,/getAllNodes\(\)/);
assert.doesNotMatch(graphSection,/source\.disconnect\(\)/);
assert.match(graphSection,/ensureOutputShell\(\)/);
assert.match(graphSection,/disconnectProcessingGraph\(\)/);
const studio=read('src/studio/studio.js');
assert.match(studio,/function renderOutputControls\(\)/);
assert.match(studio,/SET_MONITORING_ACTIVE/);
assert.match(studio,/pagehide/);
assert.match(studio,/clearTimeout\(pollingTimer\)/);
assert.doesNotMatch(offscreen,/GET_ANALYSIS_FRAME':\s*host\.setMonitoringActive/);
const manifest=JSON.parse(read('manifest.json')); const pkg=JSON.parse(read('package.json'));
assert.equal(manifest.version,'0.3.106'); assert.equal(pkg.version,manifest.version);
console.log('Headless audio stability smoke test passed.');
