import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
assert.equal(fs.existsSync(path.join(root,'src/shared/audio-devices.js')),false);
const files=['popup.html','studio.html','offscreen.html','src/popup/popup.js','src/studio/studio.js','src/background/service-worker.js','src/offscreen/offscreen.js','src/shared/presets.js'];
const runtime=files.map(read).join('\n');
for (const token of ['outputDeviceId','outputRouteStatus','setSinkId','createMediaStreamDestination','processedOutput','audioOutputSelect','topbarOutputDevice','domainOutputRoutes']) assert.equal(runtime.includes(token),false,`removed output-routing token remains: ${token}`);
const offscreen=read('src/offscreen/offscreen.js');
assert.match(offscreen,/SET_MONITORING_ACTIVE/);
assert.match(offscreen,/monitoringActive = false/);
assert.match(offscreen,/createMonitoringNodes\(\)/);
assert.match(offscreen,/destroyMonitoringNodes\(\)/);
assert.match(offscreen,/this\.source\.connect\(this\.inputGain\)/);
assert.match(offscreen,/cursor\.connect\(this\.context\.destination\)/);
assert.match(offscreen,/rebuildGraphSafely/);
assert.match(offscreen,/!this\.monitoringActive/);
assert.match(offscreen,/const meters = metersOverride \|\| this\.state\.meters \|\| createSilentMeters\(\)/);
assert.doesNotMatch(offscreen,/getPublicState\([^)]*\)\s*\{[^}]*computeMeters/s);
const studio=read('src/studio/studio.js');
assert.match(studio,/SET_MONITORING_ACTIVE/);
assert.match(studio,/pagehide/);
assert.match(studio,/clearTimeout\(pollingTimer\)/);
const manifest=JSON.parse(read('manifest.json')); const pkg=JSON.parse(read('package.json'));
assert.equal(manifest.version,'0.3.104'); assert.equal(pkg.version,manifest.version);
console.log('Headless audio stability smoke test passed.');
